### ISSUE TITLE
Change deprecated carousel type value vertical_wheel to verticalWheel

### ISSUE THREAD

**Issue by leonstyhre** [aitorciki/nostalgia-pure-DE#2]
Hi!

I have deprecated the vertical_wheel value for the carousel type property. Could you please change `vertical_wheel` to `verticalWheel` in theme.xml?

The latest 2.0.0-beta-2023-01-27 release works with the old value but the next beta release will completely remove its support. I hope this is the last theme-breaking change I make before the final 2.0.0 release.

Thanks!

**Comment by aitorciki** [comment]
Updated in f878597, thanks for the heads up!
